version: '3.8'

services:
  directory-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: directory-browser
    ports:
      - "5000:5000"
    volumes:
      # Mount the directory you want to browse
      - /mnt/nassys:/mnt/nassys:ro
      - /share/systemp:/share/systemp:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Optional: mount config file if you have one
      - ./config.ini:/app/config.ini:ro
    environment:
      # Set the root path for browsing
      - DEFAULT_ROOT_PATH=/mnt/nassys
      # Flask environment
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - directory-network

  # Optional: Add a reverse proxy with nginx for production
  nginx:
    image: nginx:alpine
    container_name: directory-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - directory-server
    restart: unless-stopped
    networks:
      - directory-network
    profiles:
      - production

networks:
  directory-network:
    driver: bridge

volumes:
  logs:
    driver: local 